### ISSUE TITLE
Fallback servers when errors during hopping

### ISSUE THREAD

**Issue by DerZombiiie** [HimbeerserverDE/mt-multiserver-proxy#91]
specifically when "Access denied. Reason: Server connection closed unexpectedly."

**Comment by HimbeerserverDE** [comment]
https://github.com/HimbeerserverDE/mt-multiserver-proxy/blob/main/server_conn.go#L111 is where to handle it

**Comment by HimbeerserverDE** [comment]
Why don't we just warn the user? And make Hop work even if you aren't connected to a server if you were connected to one earlier? So that the user can switch to a working server if anything breaks. Of course you could just reconnect.

IIRC errors returned by Hop are usually the result of something failing at the proxy level, e.g. issues with the auth db or a wrong server address in the config. It's much more likely to encounter a connection error or a kick which could be handled normally to fall back.

The Hop function could return a boolean indicating whether fallback is recommended or use a custom error type.

This isn't an easy issue, unlabelling.

**Comment by HimbeerserverDE** [comment]
This is now implemented. The `Hop` method handles fallbacks as well as saving the last server. The `HopRaw` method works like the previous version of `Hop` except it doesn't save the last server anymore.
